---
Name: graphqlroutes
---
SilverStripe\Control\Director:
  rules:
    'graphql': 'SilverStripe\GraphQL\Controller'
---
only:
  environment: 'dev'
---
SilverStripe\Control\Director:
  rules:
    'dev/graphiql': 'SilverStripe\GraphQL\GraphiQLController'
